---
- hosts: nexus
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
  - name: Get interface information in JSON format
    cisco.nxos.nxos_command:
      commands: show interface brief | json
    register: interface

  - name: Extract only ethernet attributes from all interfaces
    ansible.builtin.set_fact: 
      extracted: "{{ interface | json_query('stdout[0].TABLE_interface.ROW_interface[?type==`eth`]') }}"

  - name: Generate interface information file in CSV format
    ansible.builtin.copy:
      content: |
        host,interface,state,speed,portmode
        {% for host in ansible_play_hosts %}
        {% for item in extracted %}
        {{ host }},{{ item['interface'] }},{{ item['state'] }},{{ item['speed'] }},{{ item['portmode'] }}
        {% endfor %}
        {% endfor %}
      dest: interfaces.csv